CREATE TABLE "MYSCHEMANAME"."EG_CITY_CODE"  (
		  "CITY_NM" VARCHAR(50 OCTETS) NOT NULL , 
		  "CD" CHAR(3 OCTETS) NOT NULL )   
		 IN "IBMDB2SAMPLEREL"  
		 ORGANIZE BY ROW
 ;
ALTER TABLE "MYSCHEMANAME"."EG_CITY_CODE" 
	ADD CONSTRAINT "EG_CITY_CODE_PK" PRIMARY KEY
		("CD")
;

GRANT CONTROL ON TABLE "MYSCHEMANAME"."EG_CITY_CODE" TO USER "ADMINISTRATOR" 
;


CREATE TABLE "MYSCHEMANAME"."EG_PRODUCT_TYPE"  (
		  "ID" INTEGER NOT NULL , 
		  "PRODUCT_NM" VARCHAR(50 OCTETS) NOT NULL )   
		 IN "IBMDB2SAMPLEREL"  
		 ORGANIZE BY ROW
 ;
ALTER TABLE "MYSCHEMANAME"."EG_PRODUCT_TYPE" 
	ADD CONSTRAINT "EG_PRODUCT_TYPE_PK" PRIMARY KEY
		("ID")
;

GRANT CONTROL ON TABLE "MYSCHEMANAME"."EG_PRODUCT_TYPE" TO USER "ADMINISTRATOR" 
;


CREATE TABLE "MYSCHEMANAME"."EG_PRODUCT_PURCHASE"  (
		  "ID" INTEGER NOT NULL , 
		  "RECEIPT_ID" VARCHAR(15 OCTETS) NOT NULL , 
		  "PURCHASE_DT" TIMESTAMP NOT NULL , 
		  "PURCHASE_AMT" DOUBLE NOT NULL , 
		  "COUNTRY" VARCHAR(50 OCTETS) NOT NULL , 
		  "CITY_CD" CHAR(3 OCTETS) NOT NULL , 
		  "PRODUCT_TP" INTEGER NOT NULL )   
		 IN "IBMDB2SAMPLEREL"  
		 ORGANIZE BY ROW
 ;
ALTER TABLE "MYSCHEMANAME"."EG_PRODUCT_PURCHASE" 
	ADD CONSTRAINT "PRODUCT_PURCHASE_PK" PRIMARY KEY
		("ID")
;

ALTER TABLE "MYSCHEMANAME"."EG_PRODUCT_PURCHASE" 
	ADD CONSTRAINT "EG_PRODUCT_PURCHASE_EG_CITY_CODE_FK" FOREIGN KEY
		("CITY_CD")
	REFERENCES "MYSCHEMANAME"."EG_CITY_CODE"
		("CD")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION
;

GRANT CONTROL ON TABLE "MYSCHEMANAME"."EG_PRODUCT_PURCHASE" TO USER "ADMINISTRATOR" 
;
