REATE TABLE "MYSHEMANAME"."SS_FILTER_CONFIG"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
		  "VIEW_NAME" VARCHAR(15 OCTETS) NOT NULL , 
		  "FILTER_DISPLAY_NAME" VARCHAR(50 OCTETS) NOT NULL , 
		  "DB_COLUMN_NAME" VARCHAR(50 OCTETS) NOT NULL , 
		  "TYPE" VARCHAR(10 OCTETS) NOT NULL , 
		  "FILTER_QRY" CLOB(1000 OCTETS) LOGGED NOT COMPACT NOT NULL , 
		  "CACHE_QRY" INTEGER NOT NULL , 
		  "APPLY_FILTER" VARCHAR(250 OCTETS) )   
		 IN "IBMDB2SAMPLEREL"  
		 ORGANIZE BY ROW;

ALTER TABLE "MYSHEMANAME"."SS_FILTER_CONFIG" PCTFREE 0;
GRANT CONTROL ON TABLE "MYSHEMANAME"."SS_FILTER_CONFIG" TO USER "ADMINISTRATOR";

ALTER TABLE "MYSHEMANAME"."SS_FILTER_CONFIG" 
	ADD CONSTRAINT "FILTER_CONFIG_PK" PRIMARY KEY
		("ID",
		 "VIEW_NAME");

CREATE TABLE "MYSHEMANAME"."SS_SORT_CONFIG"  (
		  "VIEW_NAME" VARCHAR(15 OCTETS) NOT NULL , 
		  "DISPLAY_NAME" VARCHAR(100 OCTETS) NOT NULL , 
		  "DB_COLUMN_NAME" VARCHAR(100 OCTETS) NOT NULL , 
		  "SORT_ORDER" VARCHAR(4 OCTETS) NOT NULL )   
		 IN "IBMDB2SAMPLEREL"  
		 ORGANIZE BY ROW;

ALTER TABLE "MYSHEMANAME"."SS_SORT_CONFIG" PCTFREE 0;
ALTER TABLE "MYSHEMANAME"."SS_SORT_CONFIG" 
	ADD CONSTRAINT "SORT_CONFIG_PK" PRIMARY KEY
		("VIEW_NAME",
		 "DISPLAY_NAME");


GRANT CONTROL ON TABLE "MYSHEMANAME"."SS_SORT_CONFIG" TO USER "ADMINISTRATOR";
