INSERT INTO PROTELDBNEW.SS_SORT_CONFIG (VIEW_NAME,DISPLAY_NAME,DB_COLUMN_NAME,SORT_ORDER) VALUES 
('Example1','ID','ID','ASC')
,('Example1','City','CITY','ASC')
,('Example1','Purchase Date','PURCHASE_DT','ASC')
;